name : Playwright Tests
on :
  push :
    branches: [main]
jobs : 
    Playwrighttests:
      runs-on: ubuntu-latest
      container : 
       image : mcr.microsoft.com/playwright:v1.29.1-focal
       env : 
        ADMIN_PASSWORD: ${{secrets.Admin123}}

      steps : 
        - name : checkout repository
          uses : actions/checkout@v2
          with : 
            node-verion : 16
        - name : Run tests
          run  : |
           echo "Starting the shopping store"
           chmod +x ./shopping-store-windows-386.exe &&
           ./shopping-store-windows-386.exe &
           echo "Install dependencies from lockfile"
           npm ci
           echo "Run playwright tests"
           npm run test:ci
