name : Playwright Tests
on :
  push :
    branches: [main]
jobs : 
    Playwrighttests:
      runs-on: windows-latest
      steps : 
        - name : checkout repository
          uses : actions/checkout@v2
        - name : say hello
          run  : echo hello